0000000000432240 <void BloombergLP::bslalg::ArrayPrimitives::destructiveMoveAndEmplace<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > >, BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > >(bsl::allocator_traits<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > > >::pointer, bsl::allocator_traits<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > > >::pointer*, bsl::allocator_traits<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > > >::pointer, bsl::allocator_traits<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > > >::pointer, bsl::allocator_traits<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > > >::pointer, bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > >, BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > >&&)>:
M0000000000000000:	pushq	%rbp	;  1 bytes
M0000000000000001:	pushq	%r15	;  2 bytes
M0000000000000003:	pushq	%r14	;  2 bytes
M0000000000000005:	pushq	%r13	;  2 bytes
M0000000000000007:	pushq	%r12	;  2 bytes
M0000000000000009:	pushq	%rbx	;  1 bytes
M000000000000000a:	subq	$40, %rsp	;  4 bytes
M000000000000000e:	movq	%r8, %rbp	;  3 bytes
M0000000000000011:	movq	%rcx, %r12	;  3 bytes
M0000000000000014:	movq	%rdi, %rbx	;  3 bytes
M0000000000000017:	movq	96(%rsp), %r15	;  5 bytes
M000000000000001c:	movq	%rsi, 32(%rsp)	;  5 bytes
M0000000000000021:	movq	%r8, (%rsi)	;  3 bytes
M0000000000000024:	movq	%rcx, %rax	;  3 bytes
M0000000000000027:	movq	%rdx, 24(%rsp)	;  5 bytes
M000000000000002c:	subq	%rdx, %rax	;  3 bytes
M000000000000002f:	leaq	(%rdi,%rax), %r13	;  4 bytes
M0000000000000033:	movq	%r9, 16(%rsp)	;  5 bytes
M0000000000000038:	movq	(%r9), %rdi	;  3 bytes
M000000000000003b:	movq	48(%r15), %rcx	;  4 bytes
M000000000000003f:	movq	%rcx, 48(%rbx,%rax)	;  5 bytes
M0000000000000044:	sarq	$3, %rax	;  4 bytes
M0000000000000048:	movabsq	$7905747460161236407, %r14	; 10 bytes
M0000000000000052:	imulq	%rax, %r14	;  4 bytes
M0000000000000056:	testq	%rdi, %rdi	;  3 bytes
M0000000000000059:	movq	%rbx, 8(%rsp)	;  5 bytes
M000000000000005e:	jne	0x4322b9 <void BloombergLP::bslalg::ArrayPrimitives::destructiveMoveAndEmplace<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > >, BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > >(bsl::allocator_traits<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > > >::pointer, bsl::allocator_traits<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > > >::pointer*, bsl::allocator_traits<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > > >::pointer, bsl::allocator_traits<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > > >::pointer, bsl::allocator_traits<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > > >::pointer, bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > >, BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > >&&)+0x79>	;  2 bytes
M0000000000000060:	movq	2455321(%rip), %rdi  # 6899c0 <BloombergLP::bslma::Default::s_defaultAllocator>	;  7 bytes
M0000000000000067:	testq	%rdi, %rdi	;  3 bytes
M000000000000006a:	jne	0x4322b9 <void BloombergLP::bslalg::ArrayPrimitives::destructiveMoveAndEmplace<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > >, BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > >(bsl::allocator_traits<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > > >::pointer, bsl::allocator_traits<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > > >::pointer*, bsl::allocator_traits<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > > >::pointer, bsl::allocator_traits<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > > >::pointer, bsl::allocator_traits<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > > >::pointer, bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > >, BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > >&&)+0x79>	;  2 bytes
M000000000000006c:	callq	0x43d890 <BloombergLP::bslma::Default::determineAndReturnDefaultAllocator()>	;  5 bytes
M0000000000000071:	movq	8(%rsp), %rbx	;  5 bytes
M0000000000000076:	movq	%rax, %rdi	;  3 bytes
M0000000000000079:	movq	32(%r15), %rax	;  4 bytes
M000000000000007d:	movq	%rax, 32(%r13)	;  4 bytes
M0000000000000081:	movups	(%r15), %xmm0	;  4 bytes
M0000000000000085:	movups	16(%r15), %xmm1	;  5 bytes
M000000000000008a:	movups	%xmm1, 16(%r13)	;  5 bytes
M000000000000008f:	movups	%xmm0, (%r13)	;  5 bytes
M0000000000000094:	imulq	$56, %r14, %rax	;  4 bytes
M0000000000000098:	movq	%rdi, 40(%rbx,%rax)	;  5 bytes
M000000000000009d:	cmpq	$23, 32(%rbx,%rax)	;  6 bytes
M00000000000000a3:	je	0x432345 <void BloombergLP::bslalg::ArrayPrimitives::destructiveMoveAndEmplace<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > >, BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > >(bsl::allocator_traits<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > > >::pointer, bsl::allocator_traits<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > > >::pointer*, bsl::allocator_traits<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > > >::pointer, bsl::allocator_traits<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > > >::pointer, bsl::allocator_traits<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > > >::pointer, bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > >, BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > >&&)+0x105>	;  2 bytes
M00000000000000a5:	leaq	32(%rbx,%rax), %r14	;  5 bytes
M00000000000000aa:	movq	24(%r15), %rcx	;  4 bytes
M00000000000000ae:	cmpq	$23, %rcx	;  4 bytes
M00000000000000b2:	movl	$23, %esi	;  5 bytes
M00000000000000b7:	cmovaq	%rcx, %rsi	;  4 bytes
M00000000000000bb:	movq	$0, (%r13)	;  8 bytes
M00000000000000c3:	movq	%rcx, 24(%rbx,%rax)	;  5 bytes
M00000000000000c8:	movq	%rsi, (%r14)	;  3 bytes
M00000000000000cb:	cmpq	$24, %rcx	;  4 bytes
M00000000000000cf:	jb	0x432324 <void BloombergLP::bslalg::ArrayPrimitives::destructiveMoveAndEmplace<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > >, BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > >(bsl::allocator_traits<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > > >::pointer, bsl::allocator_traits<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > > >::pointer*, bsl::allocator_traits<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > > >::pointer, bsl::allocator_traits<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > > >::pointer, bsl::allocator_traits<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > > >::pointer, bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > >, BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > >&&)+0xe4>	;  2 bytes
M00000000000000d1:	incq	%rsi	;  3 bytes
M00000000000000d4:	movq	(%rdi), %rax	;  3 bytes
M00000000000000d7:	callq	*16(%rax)	;  3 bytes
M00000000000000da:	movq	%rax, (%r13)	;  4 bytes
M00000000000000de:	cmpq	$23, (%r14)	;  4 bytes
M00000000000000e2:	jne	0x432327 <void BloombergLP::bslalg::ArrayPrimitives::destructiveMoveAndEmplace<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > >, BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > >(bsl::allocator_traits<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > > >::pointer, bsl::allocator_traits<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > > >::pointer*, bsl::allocator_traits<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > > >::pointer, bsl::allocator_traits<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > > >::pointer, bsl::allocator_traits<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > > >::pointer, bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > >, BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > >&&)+0xe7>	;  2 bytes
M00000000000000e4:	movq	%r13, %rax	;  3 bytes
M00000000000000e7:	movq	-8(%r14), %rdx	;  4 bytes
M00000000000000eb:	incq	%rdx	;  3 bytes
M00000000000000ee:	je	0x432345 <void BloombergLP::bslalg::ArrayPrimitives::destructiveMoveAndEmplace<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > >, BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > >(bsl::allocator_traits<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > > >::pointer, bsl::allocator_traits<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > > >::pointer*, bsl::allocator_traits<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > > >::pointer, bsl::allocator_traits<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > > >::pointer, bsl::allocator_traits<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > > >::pointer, bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > >, BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > >&&)+0x105>	;  2 bytes
M00000000000000f0:	cmpq	$23, 32(%r15)	;  5 bytes
M00000000000000f5:	je	0x43233a <void BloombergLP::bslalg::ArrayPrimitives::destructiveMoveAndEmplace<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > >, BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > >(bsl::allocator_traits<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > > >::pointer, bsl::allocator_traits<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > > >::pointer*, bsl::allocator_traits<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > > >::pointer, bsl::allocator_traits<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > > >::pointer, bsl::allocator_traits<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > > >::pointer, bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > >, BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > >&&)+0xfa>	;  2 bytes
M00000000000000f7:	movq	(%r15), %r15	;  3 bytes
M00000000000000fa:	movq	%rax, %rdi	;  3 bytes
M00000000000000fd:	movq	%r15, %rsi	;  3 bytes
M0000000000000100:	callq	0x403ea0 <memcpy@plt>	;  5 bytes
M0000000000000105:	leaq	56(%r13), %r15	;  4 bytes
M0000000000000109:	movq	16(%rsp), %rax	;  5 bytes
M000000000000010e:	movq	(%rax), %rax	;  3 bytes
M0000000000000111:	movq	%rax, (%rsp)	;  4 bytes
M0000000000000115:	movq	%rsp, %rcx	;  3 bytes
M0000000000000118:	movq	%r15, %rdi	;  3 bytes
M000000000000011b:	movq	%r12, %rsi	;  3 bytes
M000000000000011e:	movq	%rbp, %rdx	;  3 bytes
M0000000000000121:	xorl	%r8d, %r8d	;  3 bytes
M0000000000000124:	callq	0x4320d0 <void BloombergLP::bslalg::ArrayPrimitives_Imp::moveIfNoexcept<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > >, bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > > >(BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > >*, BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > >*, BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > >*, bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > >, BloombergLP::bslmf::MetaInt<0>*)>	;  5 bytes
M0000000000000129:	cmpq	%rbp, %r12	;  3 bytes
M000000000000012c:	movq	32(%rsp), %r14	;  5 bytes
M0000000000000131:	je	0x4323a7 <void BloombergLP::bslalg::ArrayPrimitives::destructiveMoveAndEmplace<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > >, BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > >(bsl::allocator_traits<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > > >::pointer, bsl::allocator_traits<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > > >::pointer*, bsl::allocator_traits<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > > >::pointer, bsl::allocator_traits<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > > >::pointer, bsl::allocator_traits<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > > >::pointer, bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > >, BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > >&&)+0x167>	;  2 bytes
M0000000000000133:	movq	%r12, %rbx	;  3 bytes
M0000000000000136:	jmp	0x432391 <void BloombergLP::bslalg::ArrayPrimitives::destructiveMoveAndEmplace<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > >, BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > >(bsl::allocator_traits<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > > >::pointer, bsl::allocator_traits<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > > >::pointer*, bsl::allocator_traits<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > > >::pointer, bsl::allocator_traits<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > > >::pointer, bsl::allocator_traits<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > > >::pointer, bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > >, BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > >&&)+0x151>	;  2 bytes
M0000000000000138:	nopl	(%rax,%rax)	;  8 bytes
M0000000000000140:	movq	$-1, 24(%rbx)	;  8 bytes
M0000000000000148:	addq	$56, %rbx	;  4 bytes
M000000000000014c:	cmpq	%rbx, %rbp	;  3 bytes
M000000000000014f:	je	0x4323a7 <void BloombergLP::bslalg::ArrayPrimitives::destructiveMoveAndEmplace<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > >, BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > >(bsl::allocator_traits<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > > >::pointer, bsl::allocator_traits<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > > >::pointer*, bsl::allocator_traits<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > > >::pointer, bsl::allocator_traits<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > > >::pointer, bsl::allocator_traits<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > > >::pointer, bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > >, BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > >&&)+0x167>	;  2 bytes
M0000000000000151:	cmpq	$23, 32(%rbx)	;  5 bytes
M0000000000000156:	je	0x432380 <void BloombergLP::bslalg::ArrayPrimitives::destructiveMoveAndEmplace<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > >, BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > >(bsl::allocator_traits<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > > >::pointer, bsl::allocator_traits<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > > >::pointer*, bsl::allocator_traits<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > > >::pointer, bsl::allocator_traits<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > > >::pointer, bsl::allocator_traits<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > > >::pointer, bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > >, BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > >&&)+0x140>	;  2 bytes
M0000000000000158:	movq	(%rbx), %rsi	;  3 bytes
M000000000000015b:	movq	40(%rbx), %rdi	;  4 bytes
M000000000000015f:	movq	(%rdi), %rax	;  3 bytes
M0000000000000162:	callq	*24(%rax)	;  3 bytes
M0000000000000165:	jmp	0x432380 <void BloombergLP::bslalg::ArrayPrimitives::destructiveMoveAndEmplace<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > >, BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > >(bsl::allocator_traits<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > > >::pointer, bsl::allocator_traits<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > > >::pointer*, bsl::allocator_traits<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > > >::pointer, bsl::allocator_traits<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > > >::pointer, bsl::allocator_traits<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > > >::pointer, bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > >, BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > >&&)+0x140>	;  2 bytes
M0000000000000167:	movq	%r12, (%r14)	;  3 bytes
M000000000000016a:	subq	%r12, %rbp	;  3 bytes
M000000000000016d:	addq	%rbp, %r15	;  3 bytes
M0000000000000170:	movq	16(%rsp), %rax	;  5 bytes
M0000000000000175:	movq	(%rax), %rax	;  3 bytes
M0000000000000178:	movq	%rax, (%rsp)	;  4 bytes
M000000000000017c:	movq	%rsp, %rcx	;  3 bytes
M000000000000017f:	movq	8(%rsp), %rdi	;  5 bytes
M0000000000000184:	movq	24(%rsp), %rbp	;  5 bytes
M0000000000000189:	movq	%rbp, %rsi	;  3 bytes
M000000000000018c:	movq	%r12, %rdx	;  3 bytes
M000000000000018f:	xorl	%r8d, %r8d	;  3 bytes
M0000000000000192:	callq	0x4320d0 <void BloombergLP::bslalg::ArrayPrimitives_Imp::moveIfNoexcept<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > >, bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > > >(BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > >*, BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > >*, BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > >*, bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > >, BloombergLP::bslmf::MetaInt<0>*)>	;  5 bytes
M0000000000000197:	cmpq	%r12, %rbp	;  3 bytes
M000000000000019a:	je	0x432417 <void BloombergLP::bslalg::ArrayPrimitives::destructiveMoveAndEmplace<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > >, BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > >(bsl::allocator_traits<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > > >::pointer, bsl::allocator_traits<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > > >::pointer*, bsl::allocator_traits<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > > >::pointer, bsl::allocator_traits<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > > >::pointer, bsl::allocator_traits<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > > >::pointer, bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > >, BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > >&&)+0x1d7>	;  2 bytes
M000000000000019c:	movq	%rbp, %rbx	;  3 bytes
M000000000000019f:	jmp	0x432401 <void BloombergLP::bslalg::ArrayPrimitives::destructiveMoveAndEmplace<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > >, BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > >(bsl::allocator_traits<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > > >::pointer, bsl::allocator_traits<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > > >::pointer*, bsl::allocator_traits<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > > >::pointer, bsl::allocator_traits<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > > >::pointer, bsl::allocator_traits<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > > >::pointer, bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > >, BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > >&&)+0x1c1>	;  2 bytes
M00000000000001a1:	nopw	%cs:(%rax,%rax)	; 10 bytes
M00000000000001ab:	nopl	(%rax,%rax)	;  5 bytes
M00000000000001b0:	movq	$-1, 24(%rbx)	;  8 bytes
M00000000000001b8:	addq	$56, %rbx	;  4 bytes
M00000000000001bc:	cmpq	%rbx, %r12	;  3 bytes
M00000000000001bf:	je	0x432417 <void BloombergLP::bslalg::ArrayPrimitives::destructiveMoveAndEmplace<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > >, BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > >(bsl::allocator_traits<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > > >::pointer, bsl::allocator_traits<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > > >::pointer*, bsl::allocator_traits<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > > >::pointer, bsl::allocator_traits<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > > >::pointer, bsl::allocator_traits<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > > >::pointer, bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > >, BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > >&&)+0x1d7>	;  2 bytes
M00000000000001c1:	cmpq	$23, 32(%rbx)	;  5 bytes
M00000000000001c6:	je	0x4323f0 <void BloombergLP::bslalg::ArrayPrimitives::destructiveMoveAndEmplace<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > >, BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > >(bsl::allocator_traits<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > > >::pointer, bsl::allocator_traits<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > > >::pointer*, bsl::allocator_traits<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > > >::pointer, bsl::allocator_traits<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > > >::pointer, bsl::allocator_traits<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > > >::pointer, bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > >, BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > >&&)+0x1b0>	;  2 bytes
M00000000000001c8:	movq	(%rbx), %rsi	;  3 bytes
M00000000000001cb:	movq	40(%rbx), %rdi	;  4 bytes
M00000000000001cf:	movq	(%rdi), %rax	;  3 bytes
M00000000000001d2:	callq	*24(%rax)	;  3 bytes
M00000000000001d5:	jmp	0x4323f0 <void BloombergLP::bslalg::ArrayPrimitives::destructiveMoveAndEmplace<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > >, BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > >(bsl::allocator_traits<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > > >::pointer, bsl::allocator_traits<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > > >::pointer*, bsl::allocator_traits<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > > >::pointer, bsl::allocator_traits<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > > >::pointer, bsl::allocator_traits<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > > >::pointer, bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > >, BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > >&&)+0x1b0>	;  2 bytes
M00000000000001d7:	movq	%rbp, (%r14)	;  3 bytes
M00000000000001da:	addq	$40, %rsp	;  4 bytes
M00000000000001de:	popq	%rbx	;  1 bytes
M00000000000001df:	popq	%r12	;  2 bytes
M00000000000001e1:	popq	%r13	;  2 bytes
M00000000000001e3:	popq	%r14	;  2 bytes
M00000000000001e5:	popq	%r15	;  2 bytes
M00000000000001e7:	popq	%rbp	;  1 bytes
M00000000000001e8:	retq		;  1 bytes
M00000000000001e9:	movq	%rax, %rbx	;  3 bytes
M00000000000001ec:	cmpq	%r15, %r13	;  3 bytes
M00000000000001ef:	jne	0x432451 <void BloombergLP::bslalg::ArrayPrimitives::destructiveMoveAndEmplace<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > >, BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > >(bsl::allocator_traits<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > > >::pointer, bsl::allocator_traits<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > > >::pointer*, bsl::allocator_traits<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > > >::pointer, bsl::allocator_traits<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > > >::pointer, bsl::allocator_traits<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > > >::pointer, bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > >, BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > >&&)+0x211>	;  2 bytes
M00000000000001f1:	movq	%rbx, %rdi	;  3 bytes
M00000000000001f4:	callq	0x403e50 <_Unwind_Resume@plt>	;  5 bytes
M00000000000001f9:	movq	%rax, %rbx	;  3 bytes
M00000000000001fc:	jmp	0x432451 <void BloombergLP::bslalg::ArrayPrimitives::destructiveMoveAndEmplace<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > >, BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > >(bsl::allocator_traits<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > > >::pointer, bsl::allocator_traits<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > > >::pointer*, bsl::allocator_traits<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > > >::pointer, bsl::allocator_traits<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > > >::pointer, bsl::allocator_traits<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > > >::pointer, bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > >, BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > >&&)+0x211>	;  2 bytes
M00000000000001fe:	nop		;  2 bytes
M0000000000000200:	movq	$-1, 24(%r13)	;  8 bytes
M0000000000000208:	addq	$56, %r13	;  4 bytes
M000000000000020c:	cmpq	%r13, %r15	;  3 bytes
M000000000000020f:	je	0x432431 <void BloombergLP::bslalg::ArrayPrimitives::destructiveMoveAndEmplace<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > >, BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > >(bsl::allocator_traits<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > > >::pointer, bsl::allocator_traits<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > > >::pointer*, bsl::allocator_traits<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > > >::pointer, bsl::allocator_traits<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > > >::pointer, bsl::allocator_traits<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > > >::pointer, bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > >, BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > >&&)+0x1f1>	;  2 bytes
M0000000000000211:	cmpq	$23, 32(%r13)	;  5 bytes
M0000000000000216:	je	0x432440 <void BloombergLP::bslalg::ArrayPrimitives::destructiveMoveAndEmplace<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > >, BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > >(bsl::allocator_traits<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > > >::pointer, bsl::allocator_traits<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > > >::pointer*, bsl::allocator_traits<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > > >::pointer, bsl::allocator_traits<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > > >::pointer, bsl::allocator_traits<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > > >::pointer, bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > >, BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > >&&)+0x200>	;  2 bytes
M0000000000000218:	movq	(%r13), %rsi	;  4 bytes
M000000000000021c:	movq	40(%r13), %rdi	;  4 bytes
M0000000000000220:	movq	(%rdi), %rax	;  3 bytes
M0000000000000223:	callq	*24(%rax)	;  3 bytes
M0000000000000226:	jmp	0x432440 <void BloombergLP::bslalg::ArrayPrimitives::destructiveMoveAndEmplace<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > >, BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > >(bsl::allocator_traits<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > > >::pointer, bsl::allocator_traits<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > > >::pointer*, bsl::allocator_traits<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > > >::pointer, bsl::allocator_traits<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > > >::pointer, bsl::allocator_traits<bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > > >::pointer, bsl::allocator<BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > > >, BloombergLP::bdlc::CompactedArray_CountedValue<bsl::basic_string<char, std::__1::char_traits<char>, bsl::allocator<char> > >&&)+0x200>	;  2 bytes
M0000000000000228:	movq	%rax, %rdi	;  3 bytes
M000000000000022b:	callq	0x42f650 <__clang_call_terminate>	;  5 bytes
M0000000000000230:	movq	%rax, %rdi	;  3 bytes
M0000000000000233:	callq	0x42f650 <__clang_call_terminate>	;  5 bytes
M0000000000000238:	movq	%rax, %rdi	;  3 bytes
M000000000000023b:	callq	0x42f650 <__clang_call_terminate>	;  5 bytes
